-- Re-adopting the announcements table after its migration was regenerated.
--
-- WHY THIS EXISTS
-- PR #6 added `announcements` with a hand-written migration,
-- 20260812130000_AddAnnouncementsTable. It had no .Designer.cs and left no
-- entry in ApplicationDbContextModelSnapshot, so EF did not know the table
-- existed in its model: `dotnet ef migrations has-pending-model-changes`
-- reported "Changes have been made to the model since the last migration",
-- and the next `migrations add` by anyone would have emitted a second
-- CREATE TABLE announcements.
--
-- It also carried two column bugs, both from the mapping rather than the SQL:
--   created_at was annotated MySql:ValueGenerationStrategy = IdentityColumn
--     (an identity strategy on a timestamp)
--   updated_at was annotated ComputedColumn with no computed expression
-- Both came from ValueGeneratedOnAdd() / ValueGeneratedOnAddOrUpdate() in
-- ApplicationDbContext, which claim the database produces the value. It does
-- not -- AnnouncementService sets both in C#. Those calls are removed, and
-- both columns are now plain datetime(6).
--
-- The hand-written migration was deleted and regenerated by EF as
-- 20260813053823_AddAnnouncementsTable, with a Designer and a snapshot entry.
-- Because the migration ID changed, a database that already ran the old one
-- has the wrong row in __efmigrationshistory.
--
-- WHEN TO USE WHICH
--   Database that already applied 20260812130000 (anyone who pulled PR #6
--   and ran `dotnet ef database update` before this fix):
--       run THIS script. It rewrites the history row and corrects the two
--       column definitions in place. Do not run `dotnet ef database update`
--       first -- it would try to CREATE TABLE announcements again.
--   Fresh database, or one that never applied the old migration:
--       do NOT run this script. Run `dotnet ef database update`, which
--       creates the table correctly from the regenerated migration.
--
-- Safe to run more than once: every statement is guarded.
--
-- APPLIED 2026-08-13 to MNNITRNC_New on 192.168.1.27, but only in part, and the
-- database was not in the state this script assumed. It had the announcements
-- TABLE but NO __EFMigrationsHistory row for it at all -- so PR #6's migration
-- had never been recorded, rather than recorded under the old ID. The DELETE was
-- therefore a no-op and only the INSERT IGNORE mattered.
--
-- Section 1 (the two ALTER TABLE statements) was NOT run. created_at and
-- updated_at on that database are still `timestamp` with DEFAULT_GENERATED
-- rather than `datetime(6)`. Harmless in practice -- AnnouncementService assigns
-- both in C#, so nothing depends on the database default -- but it means the
-- live schema does not match the model, and a future migration touching those
-- columns may behave unexpectedly. Worth running section 1 during a maintenance
-- window.

-- 1. Correct the two timestamp columns.
--    Guarded so the script is a no-op where the columns are already correct.
SET @fix_created := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'announcements'
      AND COLUMN_NAME = 'created_at'
      AND (EXTRA LIKE '%auto_increment%' OR EXTRA LIKE '%GENERATED%' OR DATA_TYPE <> 'datetime')
);
SET @sql := IF(@fix_created > 0,
    'ALTER TABLE `announcements` MODIFY COLUMN `created_at` datetime(6) NOT NULL',
    'SELECT "created_at already correct"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @fix_updated := (
    SELECT COUNT(*) FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'announcements'
      AND COLUMN_NAME = 'updated_at'
      AND (EXTRA LIKE '%auto_increment%' OR EXTRA LIKE '%GENERATED%' OR DATA_TYPE <> 'datetime')
);
SET @sql := IF(@fix_updated > 0,
    'ALTER TABLE `announcements` MODIFY COLUMN `updated_at` datetime(6) NOT NULL',
    'SELECT "updated_at already correct"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- 2. Replace the old migration-history row with the regenerated one, so EF
--    stops trying to create a table that is already there.
DELETE FROM `__EFMigrationsHistory`
WHERE `MigrationId` = '20260812130000_AddAnnouncementsTable';

INSERT IGNORE INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20260813053823_AddAnnouncementsTable', '8.0.10');
