import { useEffect, useState } from "react";
import { X, FileText, Download, Loader2 } from "lucide-react";
import { downloadDocument, uploadDocument } from "../../../api/documentsApi";
import { getSignedStipendFormMetadata, getAutoGeneratedStipendFormBlob } from "../../../api/fellowshipApi";

export default function StipendFormModal({
  claim,
  onClose,
  canUpload = false,
  showToast,
}) {
  const [stipendFormPreviewUrl, setStipendFormPreviewUrl] = useState(null);
  const [stipendFormLoading, setStipendFormLoading] = useState(true);
  const [stipendFormFile, setStipendFormFile] = useState(null);
  const [isUploadingStipendForm, setIsUploadingStipendForm] = useState(false);
  const [hasSignedStipendForm, setHasSignedStipendForm] = useState(false);

  const loadPreview = async () => {
    setStipendFormLoading(true);
    try {
      const docs = await getSignedStipendFormMetadata(claim.id);
      if (Array.isArray(docs) && docs.length > 0) {
        setHasSignedStipendForm(true);
        const docId = docs[0].id;
        const blob = await downloadDocument(docId);
        setStipendFormPreviewUrl(URL.createObjectURL(blob));
      } else {
        setHasSignedStipendForm(false);
        const blob = await getAutoGeneratedStipendFormBlob(claim.id);
        setStipendFormPreviewUrl(URL.createObjectURL(blob));
      }
    } catch (err) {
      showToast("Failed to load stipend form preview.", true);
    } finally {
      setStipendFormLoading(false);
    }
  };

  useEffect(() => {
    if (claim) {
      loadPreview();
    }
    return () => {
      if (stipendFormPreviewUrl) {
        URL.revokeObjectURL(stipendFormPreviewUrl);
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [claim]);

  const handleUploadStipendForm = async (e) => {
    e.preventDefault();
    if (!stipendFormFile || !claim) return;
    setIsUploadingStipendForm(true);
    try {
      const payload = new FormData();
      payload.append("File", stipendFormFile);
      payload.append("OwnerType", "FellowshipClaim");
      payload.append("OwnerId", claim.id);
      payload.append("Kind", "StipendForm");

      await uploadDocument(payload);
      showToast("Signed stipend form uploaded successfully!");
      setStipendFormFile(null);
      await loadPreview();
    } catch (err) {
      showToast("Failed to upload signed form.", true);
    } finally {
      setIsUploadingStipendForm(false);
    }
  };

  if (!claim) return null;

  return (
    <div className="fixed inset-0 z-[100000] bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4">
      <div
        className={`bg-white dark:bg-slate-800 rounded-xl w-full p-6 shadow-2xl border border-slate-200 dark:border-slate-700 space-y-4 flex flex-col transition-all max-w-4xl h-[85vh]`}
      >
        <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-700 pb-3 shrink-0">
          <div className="flex items-center gap-3">
            <h3 className="font-bold text-base text-slate-900 dark:text-slate-100 flex items-center gap-2">
              <FileText className="text-violet-600" size={20} />
              Stipend Form Preview {hasSignedStipendForm ? "(Signed Upload)" : "(Au)"}
            </h3>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
          >
            <X size={20} />
          </button>
        </div>

        {stipendFormLoading ? (
          <div className="flex-1 flex items-center justify-center text-xs text-slate-400 py-4">
            <Loader2 size={24} className="animate-spin" />
          </div>
        ) : stipendFormPreviewUrl ? (
          <div className="flex-1 bg-slate-100 dark:bg-slate-900 rounded-lg overflow-hidden relative min-h-[400px]">
            <iframe
              src={stipendFormPreviewUrl}
              className="w-full h-full border-0"
              title="Document Preview"
            />
          </div>
        ) : (
          <p className="text-xs text-slate-500 dark:text-slate-400 py-4">
            Failed to load document preview.
          </p>
        )}

        {/* Upload section */}
        {canUpload && (
          <div className="pt-3 border-t border-slate-200 dark:border-slate-700 shrink-0">
            <p className="text-xs font-semibold text-slate-700 dark:text-slate-200 mb-2">
              Upload Signed Form
            </p>
            <form onSubmit={handleUploadStipendForm} className="flex items-center gap-3">
              <input
                type="file"
                accept=".pdf"
                onChange={(e) => setStipendFormFile(e.target.files[0])}
                className="flex-1 text-sm text-slate-500 dark:text-slate-400 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-xs file:font-semibold file:bg-violet-50 file:text-violet-700 hover:file:bg-violet-100 dark:file:bg-violet-900/30 dark:file:text-violet-300"
              />
              <button
                type="submit"
                disabled={!stipendFormFile || isUploadingStipendForm}
                className="px-4 py-2 bg-violet-600 hover:bg-violet-700 disabled:opacity-50 text-white text-xs font-semibold rounded-lg flex items-center gap-2 transition"
              >
                {isUploadingStipendForm ? (
                  <Loader2 size={14} className="animate-spin" />
                ) : (
                  <Download size={14} className="rotate-180" />
                )}
                Upload
              </button>
            </form>
            <p className="text-[10px] text-slate-500 mt-1">
              Upload a signed PDF copy to replace the auone.
            </p>
          </div>
        )}

        <div className="flex justify-between pt-2 shrink-0 border-t border-slate-200 dark:border-slate-700 mt-2">
          {stipendFormPreviewUrl && (
            <a
              href={stipendFormPreviewUrl}
              download={`stipend-form-${claim?.id}.pdf`}
              className="px-4 py-2 bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 text-xs font-semibold rounded-lg hover:bg-blue-100 dark:hover:bg-blue-900/50 transition flex items-center gap-1.5"
            >
              <Download size={14} /> Download Form
            </a>
          )}
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-200 dark:bg-slate-700 text-slate-800 dark:text-slate-200 text-xs font-semibold rounded-lg hover:bg-slate-300 dark:hover:bg-slate-600 transition"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
