import { useState, useEffect, useCallback, useRef } from "react";
import { useTheme } from "../layout/useTheme";
import { useAuth } from "../auth/useAuth";
import {
  Award,
  CheckCircle2,
  XCircle,
  FileText,
  Eye,
  Send,
  Search,
  Filter,
  UserCheck,
  Building2,
  Calendar,
  IndianRupee,
  AlertCircle,
  X,
  Loader2,
  Clock,
  RotateCcw,
  ChevronDown,
  ChevronUp,
  AlertTriangle,
  Download,
  ArrowLeft,
} from "lucide-react";
import {
  listAllFellowshipClaims,
  listMyProjectFellowshipClaims,
  getClaimSteps,
  approveClaim,
  rejectClaim,
  returnClaim,
  recommendAmount,
  getHraSlipDocuments,
  getSignedStipendFormMetadata,
  getAutoGeneratedStipendFormBlob,
} from "../api/fellowshipApi";
import { WORKFLOW_STAGE_LABELS } from "../constants/procurementEnums";
import { MONTHS } from "../constants/fellowshipEnums";
import { formatCurrency } from "./projects/utils/currency";
import { documentDownloadPath, downloadDocument } from "../api/documentsApi";
import HraOverrideModal from "./fellowship/components/HraOverrideModal";
import StipendFormModal from "./fellowship/components/StipendFormModal";
import ProcessClaimModal from "./fellowship/components/ProcessClaimModal";
import FellowshipBulkQueuePage from "./fellowship/FellowshipBulkQueuePage";
import FellowshipVoucherSelectionPage from "./fellowship/FellowshipVoucherSelectionPage";

const STAGE = {
  WITH_PI: "WithPIFellowship",
  WITH_HOD: "WithHODFellowship",
  WITH_DA: "WithDAFellowship",
  WITH_SUPERINTENDENT: "WithSuperintendentFellowship",
  WITH_DR: "WithDRFellowship",
  WITH_DEAN: "WithDeanFellowship",
  RETURNED_HOD: "ReturnedByHODToPI",
  RETURNED_DA: "ReturnedByDAToPI",
  RETURNED_SUPERINTENDENT: "ReturnedBySuperintendentToPI",
  RETURNED_DR: "ReturnedByDRToPI",
  RETURNED_DEAN: "ReturnedByDeanToPI",
  APPROVED: "Approved",
  REJECTED: "Rejected",
  RAISED: "Raised",       // legacy / migration safety
};

// Legacy generic stages that semantically mean "PI approved → now with HOD".
// Claims created before the fellowship seeder added WithHODFellowship land here.
const HOD_LEGACY_STAGES = new Set([
  "SignedCopyUploaded",
  "Assigned",
  "Forwarded",
  "ForwardedOSRC",
]);

// Legacy generic stages that semantically mean "HOD approved → now with Dean".
const DEAN_LEGACY_STAGES = new Set([
  "ForwardedDR",
  "Director",
]);

const ACTION_ICON = {
  Raise: <Clock size={13} className="text-blue-500" />,
  Approve: <CheckCircle2 size={13} className="text-emerald-500" />,
  Reject: <XCircle size={13} className="text-red-500" />,
  Return: <RotateCcw size={13} className="text-amber-500" />,
  Forward: <Send size={13} className="text-violet-500" />,
};

const ACTION_LABEL = {
  Raise: "Raised",
  Approve: "Approved / Forwarded",
  Reject: "Rejected",
  Return: "Returned to PI",
  Forward: "Forwarded",
};

const monthLabel = (m) => MONTHS.find((x) => x.value === m)?.label ?? m;

function stageColor(stage) {
  switch (stage) {
    case STAGE.WITH_PI:
    case STAGE.RAISED:
      return "bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300";
    case STAGE.WITH_HOD:
      return "bg-violet-100 text-violet-800 dark:bg-violet-900/40 dark:text-violet-300";
    case STAGE.WITH_DA:
      return "bg-fuchsia-100 text-fuchsia-800 dark:bg-fuchsia-900/40 dark:text-fuchsia-300";
    case STAGE.WITH_SUPERINTENDENT:
      return "bg-purple-100 text-purple-800 dark:bg-purple-900/40 dark:text-purple-300";
    case STAGE.WITH_DR:
      return "bg-pink-100 text-pink-800 dark:bg-pink-900/40 dark:text-pink-300";
    case STAGE.WITH_DEAN:
      return "bg-indigo-100 text-indigo-800 dark:bg-indigo-900/40 dark:text-indigo-300";
    case STAGE.RETURNED_HOD:
    case STAGE.RETURNED_DA:
    case STAGE.RETURNED_SUPERINTENDENT:
    case STAGE.RETURNED_DR:
    case STAGE.RETURNED_DEAN:
      return "bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300";
    case STAGE.APPROVED:
      return "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-300";
    case STAGE.REJECTED:
      return "bg-red-100 text-red-800 dark:bg-red-900/40 dark:text-red-300";
    default:
      return "bg-slate-100 text-slate-700 dark:bg-slate-700 dark:text-slate-300";
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function mapClaim(c) {
  return {
    id: c.id,
    fellowAppointmentId: c.fellowAppointmentId,
    workflowInstanceId: c.workflowInstanceId,
    scholarName: c.scholarName,
    rollNo: c.rollNo,
    department: c.departmentName,
    projectTitle: c.projectTitle,
    piName: c.piName,
    claimMonth: c.claimMonth,
    claimYear: c.claimYear,
    stipendAmount: c.fellowshipAmount,
    hraAmount: c.hraAmount,
    hraClaimed: c.hraClaimed,
    hraIsOverridden: c.hraIsOverridden,
    hraOverrideReason: c.hraOverrideReason,
    totalAmount: c.totalAmount,
    recommendedAmount: c.recommendedAmount,
    remarks: c.remarks,
    stage: c.currentStage,
    submittedAt: c.createdAt,
  };
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function WorkflowTimeline({ claimId, returnRemarks }) {
  const [steps, setSteps] = useState([]);
  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(true);

  useEffect(() => {
    getClaimSteps(claimId)
      .then(setSteps)
      .catch(() => { })
      .finally(() => setLoading(false));
  }, [claimId]);

  return (
    <div className="mt-4 border border-slate-200 dark:border-slate-700 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center justify-between px-4 py-3 bg-slate-50 dark:bg-slate-800/60 text-sm font-semibold text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-700/60 transition"
      >
        <span className="flex items-center gap-2">
          <Clock size={14} />
          Workflow History
        </span>
        {open ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
      </button>

      {open && (
        <div className="px-4 py-3 bg-white dark:bg-slate-900 space-y-2">
          {loading ? (
            <div className="flex items-center gap-2 text-xs text-slate-400 py-2">
              <Loader2 size={14} className="animate-spin" /> Loading history…
            </div>
          ) : steps.length === 0 ? (
            <p className="text-xs text-slate-400 py-2">No history yet.</p>
          ) : (
            <ol className="relative border-l-2 border-slate-200 dark:border-slate-700 ml-2 space-y-3">
              {steps.map((step) => {
                const isReturn = step.action === "Return";
                return (
                  <li key={step.id} className="ml-5">
                    <span className="absolute -left-[9px] flex items-center justify-center w-4 h-4 rounded-full bg-white dark:bg-slate-900 ring-2 ring-slate-200 dark:ring-slate-700">
                      {ACTION_ICON[step.action] ?? <Clock size={10} className="text-slate-400" />}
                    </span>
                    <div className={`rounded-lg px-3 py-2 text-xs ${isReturn ? "bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800/50" : "bg-slate-50 dark:bg-slate-800/40"}`}>
                      <div className="flex flex-wrap items-center gap-x-2 gap-y-0.5">
                        <span className="font-semibold text-slate-800 dark:text-slate-200">
                          {ACTION_LABEL[step.action] ?? step.action}
                        </span>
                        <span className="text-slate-400">by</span>
                        <span className="font-medium text-slate-700 dark:text-slate-300">
                          {step.actorName}
                        </span>
                        <span className="text-slate-400">·</span>
                        <span className="text-slate-400">
                          {new Date(step.timestamp).toLocaleString("en-IN", {
                            day: "2-digit", month: "short", year: "numeric",
                            hour: "2-digit", minute: "2-digit",
                          })}
                        </span>
                        <span className="ml-auto inline-flex px-1.5 py-0.5 rounded text-[10px] font-semibold bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300">
                          {WORKFLOW_STAGE_LABELS[step.stage] ?? step.stage}
                        </span>
                      </div>
                      {step.remarks && (
                        <p className={`mt-1 leading-relaxed ${isReturn ? "text-amber-800 dark:text-amber-300 font-medium" : "text-slate-600 dark:text-slate-400"}`}>
                          {isReturn && <span className="font-bold">Return reason: </span>}
                          {step.remarks}
                        </p>
                      )}
                    </div>
                  </li>
                );
              })}
            </ol>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Main page ────────────────────────────────────────────────────────────────

export default function FellowshipApprovalPage() {
  useTheme();
  const { user } = useAuth();
  const userRoles = user?.roles || [];
  const isFaculty = userRoles.includes("Faculty");
  const isHOD = userRoles.includes("HOD");
  const isDA = userRoles.includes("DealingAssistant") || userRoles.includes("RegularStaff");
  const isSuperintendent = userRoles.includes("Superintendent");
  const isDR = userRoles.includes("DeputyRegistrar");
  const isDean = userRoles.includes("Dean");
  const isSuperAdmin = userRoles.includes("SuperAdmin") || userRoles.includes("Director");

  // ── State ──────────────────────────────────────────────────────────────────
  const [claims, setClaims] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [filterTab, setFilterTab] = useState("ACTION_NEEDED");
  const [expandedClaimId, setExpandedClaimId] = useState(null);

  const [showActionModal, setShowActionModal] = useState(false);
  const [selectedClaim, setSelectedClaim] = useState(null);
  const [actionType, setActionType] = useState("APPROVE"); // APPROVE | REJECT | RETURN
  const [remarks, setRemarks] = useState("");
  const [recommendedAmountDraft, setRecommendedAmountDraft] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [toastMessage, setToastMessage] = useState({ text: "", error: false });

  const [showHraSlipModal, setShowHraSlipModal] = useState(false);
  const [hraSlipDocuments, setHraSlipDocuments] = useState([]);
  const [hraSlipLoading, setHraSlipLoading] = useState(false);
  const [previewDocUrl, setPreviewDocUrl] = useState(null);

  const closeHraSlipModal = () => {
    setShowHraSlipModal(false);
    if (previewDocUrl) {
      URL.revokeObjectURL(previewDocUrl);
      setPreviewDocUrl(null);
    }
  };

  const [showStipendFormModal, setShowStipendFormModal] = useState(false);
  const [showProcessModal, setShowProcessModal] = useState(false);
  const [activeStipendClaim, setActiveStipendClaim] = useState(null);

  const closeStipendFormModal = () => {
    setShowStipendFormModal(false);
    setActiveStipendClaim(null);
  };

  // ── Derived role context ───────────────────────────────────────────────────
  const pageTitle = isFaculty
    ? "Fellowship Claims — PI Queue"
    : isHOD
      ? "Fellowship Claims — HOD Queue"
      : isDA
        ? "Fellowship Claims — DA Queue"
        : isSuperintendent
          ? "Fellowship Claims — Superintendent Queue"
          : isDR
            ? "Fellowship Claims — DR Queue"
            : isDean
              ? "Fellowship Claims — Dean Queue"
              : "Fellowship Claims — All";

  const pageDesc = isFaculty
    ? "Review fellowship claims from your project's scholars and forward to HOD."
    : isHOD
      ? "Review claims forwarded by PI and approve or return for revision."
      : isDA
        ? "Review claims forwarded by HOD and approve or return for revision."
        : isSuperintendent
          ? "Review claims forwarded by DA and approve or return for revision."
          : isDR
            ? "Review claims forwarded by Superintendent and approve or return for revision."
            : isDean
              ? "Give final approval on claims forwarded by DR."
              : "All fellowship claims across the institute.";

  // ── Data ───────────────────────────────────────────────────────────────────
  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const raw = isFaculty
        ? await listMyProjectFellowshipClaims()
        : await listAllFellowshipClaims();
      if (Array.isArray(raw)) {
        setClaims(raw.map(mapClaim));
      }
    } catch (err) {
      showToast(err.message || "Failed to load claims.", true);
    } finally {
      setLoading(false);
    }
  }, [isFaculty]);

  useEffect(() => { loadData(); }, [loadData]);

  // ── Toast helper ───────────────────────────────────────────────────────────
  const showToast = (text, error = false) => {
    setToastMessage({ text, error });
    setTimeout(() => setToastMessage({ text: "", error: false }), 5000);
  };

  // ── Filter tabs (role-aware) ───────────────────────────────────────────────
  const tabs = isFaculty
    ? [
      { key: "ACTION_NEEDED", label: "Needs My Action" },
      { key: "FORWARDED", label: "Forwarded" },
      { key: "ALL", label: "All" },
    ]
    : (isHOD || isDA || isSuperintendent || isDR || isDean)
      ? [
        { key: "ACTION_NEEDED", label: "Needs My Action" },
        { key: "FORWARDED", label: "Processed / Forwarded" },
        { key: "ALL", label: "All" },
      ]
      : [
        { key: "ALL", label: "All" },
        { key: "ACTION_NEEDED", label: "Active" },
        { key: "APPROVED", label: "Approved" },
        { key: "REJECTED", label: "Rejected" },
      ];

  function claimMatchesTab(claim) {
    const s = claim.stage;
    if (filterTab === "ALL") return true;
    if (filterTab === "APPROVED") return s === STAGE.APPROVED;
    if (filterTab === "REJECTED") return s === STAGE.REJECTED;
    if (filterTab === "FORWARDED") {
      if (isFaculty) return s === STAGE.WITH_HOD || s === STAGE.WITH_DEAN || DEAN_LEGACY_STAGES.has(s);
      if (isHOD) return s !== STAGE.WITH_HOD && s !== STAGE.WITH_PI && s !== STAGE.RAISED && !HOD_LEGACY_STAGES.has(s);
      if (isDA) return s === STAGE.WITH_SUPERINTENDENT || s === STAGE.WITH_DR || s === STAGE.WITH_DEAN || s === STAGE.APPROVED;
      if (isSuperintendent) return s === STAGE.WITH_DR || s === STAGE.WITH_DEAN || s === STAGE.APPROVED;
      if (isDR) return s === STAGE.WITH_DEAN || s === STAGE.APPROVED;
      if (isDean) return s === STAGE.APPROVED;
      return false;
    }
    if (filterTab === "ACTION_NEEDED") {
      if (isFaculty) return s === STAGE.WITH_PI || s === STAGE.RAISED;
      if (isHOD) return s === STAGE.WITH_HOD || HOD_LEGACY_STAGES.has(s);
      if (isDA) return s === STAGE.WITH_DA;
      if (isSuperintendent) return s === STAGE.WITH_SUPERINTENDENT;
      if (isDR) return s === STAGE.WITH_DR;
      if (isDean) return s === STAGE.WITH_DEAN || DEAN_LEGACY_STAGES.has(s);
      // SuperAdmin / Director — show all non-terminal
      return s !== STAGE.APPROVED && s !== STAGE.REJECTED;
    }
    return true;
  }

  function claimMatchesSearch(claim) {
    const q = searchQuery.toLowerCase();
    return (
      claim.scholarName.toLowerCase().includes(q) ||
      claim.rollNo.toLowerCase().includes(q) ||
      claim.projectTitle.toLowerCase().includes(q) ||
      claim.piName.toLowerCase().includes(q)
    );
  }

  const filteredClaims = claims.filter(
    (c) => claimMatchesTab(c) && claimMatchesSearch(c)
  );

  // ── Action permissions ─────────────────────────────────────────────────────
  function canActOn(claim) {
    const s = claim.stage;
    if (isFaculty) return s === STAGE.WITH_PI || s === STAGE.RAISED;
    if (isHOD) return s === STAGE.WITH_HOD || HOD_LEGACY_STAGES.has(s);
    if (isDA) return s === STAGE.WITH_DA;
    if (isSuperintendent) return s === STAGE.WITH_SUPERINTENDENT;
    if (isDR) return s === STAGE.WITH_DR;
    if (isDean) return s === STAGE.WITH_DEAN || DEAN_LEGACY_STAGES.has(s);
    return false;
  }

  // ── Stat cards ─────────────────────────────────────────────────────────────
  const actionNeededCount = claims.filter((c) => {
    const s = c.stage;
    // For SuperAdmin/Director, show all non-terminal claims; for others use canActOn
    if (isSuperAdmin) return s !== STAGE.APPROVED && s !== STAGE.REJECTED;
    return canActOn({ stage: s });
  }).length;

  const approvedCount = claims.filter((c) => c.stage === STAGE.APPROVED).length;
  const totalValue = filteredClaims.reduce((sum, c) => sum + c.totalAmount, 0);

  const initialLoadRef = useRef(false);

  // Auto ALL tab if there are no pending actions on initial load
  useEffect(() => {
    if (!loading && !initialLoadRef.current) {
      initialLoadRef.current = true;
      if (filterTab === "ACTION_NEEDED" && actionNeededCount === 0) {
        setFilterTab("ALL");
      }
    }
  }, [loading, filterTab, actionNeededCount]);

  // ── Modal openers ──────────────────────────────────────────────────────────
  const openActionModal = (claim, type) => {
    if ((isHOD || isFaculty) && type === "APPROVE") {
      setSelectedClaim(claim);
      setShowProcessModal(true);
      return;
    }

    setSelectedClaim(claim);
    setActionType(type);
    setRemarks("");
    setRecommendedAmountDraft(
      claim.recommendedAmount != null ? String(claim.recommendedAmount) : ""
    );
    setShowActionModal(true);
  };

  const openHraSlipModal = async (claim) => {
    setShowHraSlipModal(true);
    setHraSlipLoading(true);
    try {
      const docs = await getHraSlipDocuments(claim.id);
      setHraSlipDocuments(Array.isArray(docs) ? docs : []);
    } catch (err) {
      setHraSlipDocuments([]);
      showToast("Failed to load HRA slip documents.", true);
    } finally {
      setHraSlipLoading(false);
    }
  };

  const handleDownloadHraSlip = async (docId) => {
    try {
      const blob = await downloadDocument(docId);
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `hra-slip-${docId}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      showToast("Failed to download HRA slip.", true);
    }
  };

  const handlePreviewHraSlip = async (docId) => {
    try {
      const blob = await downloadDocument(docId);
      const url = URL.createObjectURL(blob);
      setPreviewDocUrl(url);
    } catch (err) {
      showToast("Failed to load HRA slip for preview.", true);
    }
  };

  const openStipendFormModal = async (claim) => {
    setShowStipendFormModal(true);
    setActiveStipendClaim(claim);
  };

  // ── Execute action ─────────────────────────────────────────────────────────
  const handleExecuteAction = async () => {
    if (!selectedClaim || submitting) return;

    // Validate: remarks are required for reject/return
    if ((actionType === "REJECT" || actionType === "RETURN") && !remarks.trim()) {
      showToast("Remarks are required for rejection/return.", true);
      return;
    }

    setSubmitting(true);
    try {
      const id = selectedClaim.id;
      const s = selectedClaim.stage;

      // If PI is approving and entered a recommended amount, save it first.
      if (isFaculty && actionType === "APPROVE" && recommendedAmountDraft.trim()) {
        const amt = parseFloat(recommendedAmountDraft);
        if (!isNaN(amt) && amt >= 0) {
          await recommendAmount(id, { recommendedAmount: amt, remarks: null });
        }
      }

      if (actionType === "APPROVE") {
        await approveClaim(id, remarks || null);
      } else if (actionType === "REJECT") {
        await rejectClaim(id, remarks);
      } else if (actionType === "RETURN") {
        await returnClaim(id, remarks);
      }

      const labels = {
        APPROVE: isFaculty ? "approved and forwarded to HOD" : isHOD ? "approved and forwarded to DA" : isDA ? "approved and forwarded to Superintendent" : isSuperintendent ? "approved and forwarded to DR" : isDR ? "approved and forwarded to Dean" : "approved",
        REJECT: "rejected",
        RETURN: "returned to PI",
      };
      showToast(`Fellowship claim ${labels[actionType]} successfully!`);
      setShowActionModal(false);
      await loadData();
    } catch (err) {
      showToast(err.message || "Failed to execute action.", true);
    } finally {
      setSubmitting(false);
    }
  };

  // ── Return-reason banner (PI view) ─────────────────────────────────────────
  function ReturnReasonBanner({ claimId, stage }) {
    const [returnRemarks, setReturnRemarks] = useState(null);
    const [loaded, setLoaded] = useState(false);

    useEffect(() => {
      getClaimSteps(claimId).then((steps) => {
        // Most recent Return step
        const returnStep = [...steps]
          .reverse()
          .find((s) => s.action === "Return");
        setReturnRemarks(returnStep ?? null);
        setLoaded(true);
      }).catch(() => setLoaded(true));
    }, [claimId]);

    if (!loaded || !returnRemarks) return null;

    const actor =
      stage === STAGE.RETURNED_HOD ? "HOD" : stage === STAGE.RETURNED_DA ? "DA" : stage === STAGE.RETURNED_SUPERINTENDENT ? "Superintendent" : stage === STAGE.RETURNED_DR ? "DR" : stage === STAGE.RETURNED_DEAN ? "Dean" : "Reviewer";

    return (
      <div className="mt-3 flex items-start gap-2.5 px-4 py-3 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-700/50 rounded-lg">
        <AlertTriangle size={16} className="text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
        <div className="text-xs">
          <p className="font-bold text-amber-800 dark:text-amber-300">
            Returned by {returnRemarks.actorName} ({actor}) — action required
          </p>
          <p className="mt-0.5 text-amber-700 dark:text-amber-400 leading-relaxed">
            {returnRemarks.remarks}
          </p>
        </div>
      </div>
    );
  }

  // ─────────────────────────────────────────────────────────────────────────
  if (loading) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center gap-3">
        <Loader2 className="animate-spin text-blue-600" size={40} />
        <p className="text-sm font-semibold text-slate-500">Loading claims…</p>
      </div>
    );
  }

  // ── Render ────────────────────────────────────────────────────────────────
  return (
    <div className="min-h-screen bg-[#f8fafc] dark:bg-slate-900 text-[#17294c] dark:text-slate-100 transition-colors duration-200 px-3 sm:px-6 py-5">
      <div className="max-w-[1750px] mx-auto space-y-6">

        {/* Toast */}
        {toastMessage.text && (
          <div className={`fixed bottom-5 right-5 z-50 px-5 py-3 rounded-lg shadow-xl flex items-center gap-3 transition-all animate-bounce ${toastMessage.error ? "bg-red-600" : "bg-emerald-600"} text-white`}>
            {toastMessage.error ? <AlertCircle size={20} /> : <CheckCircle2 size={20} />}
            <span className="text-sm font-semibold">{toastMessage.text}</span>
          </div>
        )}

        {/* Page Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm px-6 py-5">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-blue-50 dark:bg-slate-700 flex items-center justify-center text-blue-600 dark:text-blue-400 shrink-0">
              <Award size={30} strokeWidth={1.8} />
            </div>
            <div>
              <h1 className="text-xl sm:text-2xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight">
                {pageTitle}
              </h1>
              <p className="mt-1 text-xs sm:text-sm text-slate-500 dark:text-slate-400">
                {pageDesc}
              </p>
            </div>
          </div>
        </div>

        {/* Stat Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="bg-white dark:bg-slate-800 p-5 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm flex items-center justify-between">
            <div>
              <p className="text-xs font-semibold uppercase text-slate-500 dark:text-slate-400 tracking-wider">
                {isSuperAdmin ? "Active Claims" : "Needs My Action"}
              </p>
              <h3 className="text-2xl font-extrabold text-amber-600 dark:text-amber-400 mt-1">
                {actionNeededCount}
              </h3>
            </div>
            <div className="w-10 h-10 rounded-lg bg-amber-50 dark:bg-amber-900/30 flex items-center justify-center text-amber-600 dark:text-amber-400">
              <AlertCircle size={22} />
            </div>
          </div>

          <div className="bg-white dark:bg-slate-800 p-5 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm flex items-center justify-between">
            <div>
              <p className="text-xs font-semibold uppercase text-slate-500 dark:text-slate-400 tracking-wider">
                Approved
              </p>
              <h3 className="text-2xl font-extrabold text-emerald-600 dark:text-emerald-400 mt-1">
                {approvedCount}
              </h3>
            </div>
            <div className="w-10 h-10 rounded-lg bg-emerald-50 dark:bg-emerald-900/30 flex items-center justify-center text-emerald-600 dark:text-emerald-400">
              <CheckCircle2 size={22} />
            </div>
          </div>

          <div className="bg-white dark:bg-slate-800 p-5 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm flex items-center justify-between">
            <div>
              <p className="text-xs font-semibold uppercase text-slate-500 dark:text-slate-400 tracking-wider">
                Filtered Total Value
              </p>
              <h3 className="text-2xl font-extrabold text-blue-600 dark:text-blue-400 mt-1">
                {formatCurrency(totalValue)}
              </h3>
            </div>
            <div className="w-10 h-10 rounded-lg bg-blue-50 dark:bg-blue-900/30 flex items-center justify-center text-blue-600 dark:text-blue-400">
              <IndianRupee size={22} />
            </div>
          </div>
        </div>

        {/* Filters */}
        <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="relative flex-1 max-w-md">
            <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              type="text"
              placeholder="Search by Scholar, Roll No, PI or Project…"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-300 dark:border-slate-600 rounded-lg text-sm outline-none focus:ring-2 focus:ring-blue-500 dark:text-white"
            />
          </div>

          <div className="flex items-center gap-3">
            <Filter size={16} className="text-slate-400" />
            <div className="flex items-center gap-1 bg-slate-100 dark:bg-slate-700 p-1 rounded-lg">
              {tabs.map((tab) => (
                <button
                  key={tab.key}
                  onClick={() => setFilterTab(tab.key)}
                  className={`px-3 py-1.5 rounded-md text-xs font-semibold transition ${filterTab === tab.key
                    ? "bg-white dark:bg-slate-800 text-blue-600 dark:text-blue-400 shadow-sm"
                    : "text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white"
                    }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Bulk queue (DA / Superintendent / DR / Dean only) */}
        {(isDA || isSuperintendent || isDR || isDean) && (
          <FellowshipBulkQueuePage
            stage={
              isDA ? STAGE.WITH_DA
                : isSuperintendent ? STAGE.WITH_SUPERINTENDENT
                  : isDR ? STAGE.WITH_DR
                    : STAGE.WITH_DEAN
            }
            onActed={loadData}
          />
        )}

        {(isDA || isSuperintendent || isDR || isDean) && (
          <FellowshipVoucherSelectionPage />
        )}

        {/* Claims List */}
        <div className="space-y-4">
          {filteredClaims.length === 0 ? (
            <div className="bg-white dark:bg-slate-800 p-10 rounded-xl border border-slate-200 dark:border-slate-700 text-center">
              <Award size={40} className="mx-auto text-slate-300 dark:text-slate-600 mb-3" />
              <p className="text-slate-500 dark:text-slate-400 text-sm font-medium">
                No fellowship claims match your search or filter.
              </p>
            </div>
          ) : (
            filteredClaims.map((claim) => {
              const isExpanded = expandedClaimId === claim.id;
              const canAct = canActOn(claim);
              const isReturned =
                claim.stage === STAGE.RETURNED_HOD ||
                claim.stage === STAGE.RETURNED_DA ||
                claim.stage === STAGE.RETURNED_SUPERINTENDENT ||
                claim.stage === STAGE.RETURNED_DR ||
                claim.stage === STAGE.RETURNED_DEAN;

              return (
                <div
                  key={claim.id}
                  className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm hover:shadow-md transition overflow-hidden"
                >
                  <div className="p-5">
                    <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-5">
                      {/* Left: claim info */}
                      <div className="space-y-3 flex-1 min-w-0">
                        <div className="flex flex-wrap items-center gap-2">
                          <span className="font-mono text-xs font-bold text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/40 px-2.5 py-1 rounded-md">
                            {claim.id.substring(0, 8)}…
                          </span>
                          <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">
                            {claim.scholarName}
                            {claim.rollNo && claim.rollNo !== "N/A" && (
                              <span className="font-normal text-slate-500"> ({claim.rollNo})</span>
                            )}
                          </h3>
                          <span className={`text-xs px-2.5 py-0.5 rounded-full font-semibold ${stageColor(claim.stage)}`}>
                            {WORKFLOW_STAGE_LABELS[claim.stage] ?? claim.stage}
                          </span>
                          {isReturned && isFaculty && (
                            <span className="text-xs px-2 py-0.5 rounded-full font-bold bg-amber-500 text-white animate-pulse">
                              Action Required
                            </span>
                          )}
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-1.5 text-xs text-slate-600 dark:text-slate-300">
                          <div className="flex items-center gap-2">
                            <Building2 size={14} className="text-slate-400 shrink-0" />
                            <span className="font-medium truncate">{claim.projectTitle}</span>
                          </div>
                          <div className="flex items-center gap-2">
                            <UserCheck size={14} className="text-slate-400 shrink-0" />
                            <span>PI: <strong>{claim.piName}</strong></span>
                          </div>
                          <div className="flex items-center gap-2">
                            <Calendar size={14} className="text-slate-400 shrink-0" />
                            <span>
                              Period: <strong>{monthLabel(claim.claimMonth)} {claim.claimYear}</strong>
                            </span>
                          </div>
                          <div className="flex items-center gap-2">
                            <FileText size={14} className="text-slate-400 shrink-0" />
                            <span>
                              Submitted: <strong>
                                {new Date(claim.submittedAt).toLocaleDateString("en-IN", {
                                  day: "2-digit", month: "short", year: "numeric",
                                })}
                              </strong>
                            </span>
                          </div>
                          {claim.department && (
                            <div className="flex items-center gap-2">
                              <Eye size={14} className="text-slate-400 shrink-0" />
                              <span>{claim.department}</span>
                            </div>
                          )}
                        </div>

                        {/* Return reason banner — shown to PI when claim is returned */}
                        {isFaculty && isReturned && (
                          <ReturnReasonBanner claimId={claim.id} stage={claim.stage} />
                        )}
                      </div>

                      {/* Right: amounts */}
                      <div className="bg-slate-50 dark:bg-slate-700/50 p-3.5 rounded-lg border border-slate-200 dark:border-slate-600 shrink-0 min-w-[220px]">
                        <div className="text-xs space-y-1.5">
                          <div className="flex justify-between text-slate-600 dark:text-slate-300">
                            <span>Fellowship:</span>
                            <span className="font-semibold tabular-nums">{formatCurrency(claim.stipendAmount)}</span>
                          </div>
                          {claim.hraClaimed && (
                            <div className="flex justify-between text-slate-600 dark:text-slate-300">
                              <span>HRA{claim.hraIsOverridden ? " (overridden)" : " "}:</span>
                              <span className="font-semibold tabular-nums text-blue-600 dark:text-blue-400">
                                +{formatCurrency(claim.hraAmount)}
                              </span>
                            </div>
                          )}
                          <div className="border-t border-slate-200 dark:border-slate-600 pt-1.5 flex justify-between font-bold text-sm text-slate-900 dark:text-slate-100">
                            <span>Total:</span>
                            <span className="text-emerald-600 dark:text-emerald-400 tabular-nums">
                              {formatCurrency(claim.totalAmount)}
                            </span>
                          </div>
                          {claim.recommendedAmount != null && (
                            <div className="flex justify-between text-slate-600 dark:text-slate-300 border-t border-slate-200 dark:border-slate-600 pt-1.5">
                              <span>PI Recommended:</span>
                              <span className="font-semibold tabular-nums text-violet-600 dark:text-violet-400">
                                {formatCurrency(claim.recommendedAmount)}
                              </span>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>

                    {/* Action buttons */}
                    <div className="mt-4 flex flex-wrap items-center gap-2 pt-3 border-t border-slate-100 dark:border-slate-700">
                      <button
                        onClick={() => setExpandedClaimId(isExpanded ? null : claim.id)}
                        className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 dark:bg-slate-700 dark:hover:bg-slate-600 text-slate-700 dark:text-slate-300 text-xs font-semibold rounded-lg flex items-center gap-1.5 transition"
                      >
                        <Clock size={13} />
                        {isExpanded ? "Hide History" : "View History"}
                      </button>

                      {claim.hraClaimed && (
                        <button
                          onClick={() => openHraSlipModal(claim)}
                          className="px-3 py-1.5 bg-blue-100 hover:bg-blue-200 dark:bg-blue-900/30 dark:hover:bg-blue-900/50 text-blue-700 dark:text-blue-300 text-xs font-semibold rounded-lg flex items-center gap-1.5 transition"
                        >
                          <Download size={13} />
                          HRA Slip
                        </button>
                      )}

                      <button
                        onClick={() => openStipendFormModal(claim)}
                        className="px-3 py-1.5 bg-violet-100 hover:bg-violet-200 dark:bg-violet-900/30 dark:hover:bg-violet-900/50 text-violet-700 dark:text-violet-300 text-xs font-semibold rounded-lg flex items-center gap-1.5 transition"
                      >
                        <FileText size={13} />
                        Stipend Form
                      </button>

                      {canAct && (
                        <>
                          <button
                            onClick={() => openActionModal(claim, "APPROVE")}
                            className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold rounded-lg flex items-center gap-1.5 transition shadow-sm"
                          >
                            <Send size={13} />
                            {isDean ? "Approve" : "Approve & Forward"}
                          </button>

                          {(isHOD || isDA || isSuperintendent || isDR || isDean) && (
                            <button
                              onClick={() => openActionModal(claim, "RETURN")}
                              className="px-3 py-1.5 bg-amber-500 hover:bg-amber-600 text-white text-xs font-semibold rounded-lg flex items-center gap-1.5 transition shadow-sm"
                            >
                              <RotateCcw size={13} />
                              Return to PI
                            </button>
                          )}

                          <button
                            onClick={() => openActionModal(claim, "REJECT")}
                            className="px-3 py-1.5 bg-red-600 hover:bg-red-700 text-white text-xs font-semibold rounded-lg flex items-center gap-1.5 transition shadow-sm"
                          >
                            <XCircle size={13} />
                            Reject
                          </button>
                        </>
                      )}
                    </div>
                  </div>

                  {/* Expandable workflow history */}
                  {isExpanded && (
                    <div className="px-5 pb-5">
                      <WorkflowTimeline claimId={claim.id} />
                    </div>
                  )}
                </div>
              );
            })
          )}
        </div>

        {/* Action Modal */}
        {showActionModal && selectedClaim && (
          <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4">
            <div className="bg-white dark:bg-slate-800 rounded-xl max-w-md w-full p-6 shadow-2xl border border-slate-200 dark:border-slate-700 space-y-4">
              <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-700 pb-3">
                <h3 className="font-bold text-base text-slate-900 dark:text-slate-100 flex items-center gap-2">
                  {actionType === "APPROVE" && (
                    <>
                      <CheckCircle2 className="text-emerald-600" size={20} />
                      {isFaculty ? "Approve & Forward to HOD" : isHOD ? "Approve & Forward to DA" : isDA ? "Approve & Forward to Superintendent" : isSuperintendent ? "Approve & Forward to DR" : isDR ? "Approve & Forward to Dean" : "Approve Fellowship Claim"}
                    </>
                  )}
                  {actionType === "REJECT" && (
                    <>
                      <XCircle className="text-red-600" size={20} />
                      Reject Fellowship Claim
                    </>
                  )}
                  {actionType === "RETURN" && (
                    <>
                      <RotateCcw className="text-amber-600" size={20} />
                      Return to PI for Revision
                    </>
                  )}
                </h3>
                <button
                  onClick={() => setShowActionModal(false)}
                  className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
                >
                  <X size={20} />
                </button>
              </div>

              <p className="text-xs text-slate-600 dark:text-slate-300">
                {actionType === "APPROVE" && "You are about to approve the claim of"}
                {actionType === "REJECT" && "You are about to permanently reject the claim of"}
                {actionType === "RETURN" && "You are about to return the claim of"}
                {" "}
                <strong>{selectedClaim.scholarName}</strong>
                {" "}(claim: <strong>{formatCurrency(selectedClaim.totalAmount)}</strong>).
              </p>

              {/* PI: Recommended amount field (only shown for approve action) */}
              {isFaculty && actionType === "APPROVE" && (
                <div className="space-y-1 p-3 bg-violet-50 dark:bg-violet-900/20 rounded-lg border border-violet-200 dark:border-violet-800/50">
                  <label className="block text-xs font-semibold text-violet-700 dark:text-violet-300">
                    Recommended Amount (₹)
                    <span className="text-slate-500 font-normal ml-1">— optional, your suggested pay</span>
                  </label>
                  <input
                    type="number"
                    min="0"
                    step="0.01"
                    value={recommendedAmountDraft}
                    onChange={(e) => setRecommendedAmountDraft(e.target.value)}
                    placeholder={`Default: ${formatCurrency(selectedClaim.totalAmount)}`}
                    className="w-full px-3 py-2 bg-white dark:bg-slate-700 border border-violet-300 dark:border-violet-700 rounded-lg text-xs outline-none focus:ring-2 focus:ring-violet-500 dark:text-white"
                  />
                  <p className="text-[11px] text-violet-600 dark:text-violet-400">
                    Leave blank to use the computed amount. This is the figure that will appear on the stipend form.
                  </p>
                </div>
              )}

              <div className="space-y-1">
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-200">
                  {actionType === "APPROVE"
                    ? "Remarks / Comments"
                    : actionType === "REJECT"
                      ? "Reason for Rejection"
                      : "Reason for Return to PI"}
                  {(actionType === "REJECT" || actionType === "RETURN") && (
                    <span className="text-red-500 ml-1">*</span>
                  )}
                </label>
                <textarea
                  rows={3}
                  value={remarks}
                  onChange={(e) => setRemarks(e.target.value)}
                  placeholder={
                    actionType === "APPROVE"
                      ? "Optional remarks…"
                      : actionType === "REJECT"
                        ? "State the reason for rejection (required)…"
                        : "State what needs to be revised (required — PI will see this)…"
                  }
                  className="w-full p-3 bg-slate-50 dark:bg-slate-700 border border-slate-300 dark:border-slate-600 rounded-lg text-xs outline-none focus:ring-2 focus:ring-blue-500 dark:text-white resize-none"
                />
                {(actionType === "REJECT" || actionType === "RETURN") && !remarks.trim() && (
                  <p className="text-xs text-red-500">Remarks are required.</p>
                )}
                {actionType === "RETURN" && (
                  <p className="text-[11px] text-amber-600 dark:text-amber-400 flex items-center gap-1">
                    <AlertTriangle size={11} />
                    PI will see this reason prominently before re-submitting.
                  </p>
                )}
              </div>

              <div className="flex justify-end gap-3 pt-2">
                <button
                  onClick={() => setShowActionModal(false)}
                  className="px-4 py-2 bg-slate-200 dark:bg-slate-700 text-slate-800 dark:text-slate-200 text-xs font-semibold rounded-lg hover:bg-slate-300 dark:hover:bg-slate-600 transition"
                >
                  Cancel
                </button>
                <button
                  onClick={handleExecuteAction}
                  disabled={submitting || ((actionType === "REJECT" || actionType === "RETURN") && !remarks.trim())}
                  className={`px-4 py-2 text-white text-xs font-semibold rounded-lg transition shadow-sm disabled:opacity-50 disabled:cursor-not-allowed ${actionType === "APPROVE"
                    ? "bg-emerald-600 hover:bg-emerald-700"
                    : actionType === "REJECT"
                      ? "bg-red-600 hover:bg-red-700"
                      : "bg-amber-500 hover:bg-amber-600"
                    }`}
                >
                  {submitting ? (
                    <span className="flex items-center gap-2">
                      <Loader2 size={13} className="animate-spin" /> Processing…
                    </span>
                  ) : (
                    `Confirm ${actionType === "APPROVE" ? "Approval" : actionType === "REJECT" ? "Rejection" : "Return"}`
                  )}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* HRA Slip Modal */}
        {showHraSlipModal && (
          <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4">
            <div className={`bg-white dark:bg-slate-800 rounded-xl w-full p-6 shadow-2xl border border-slate-200 dark:border-slate-700 space-y-4 flex flex-col transition-all ${previewDocUrl ? 'max-w-4xl h-[85vh]' : 'max-w-md'}`}>
              <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-700 pb-3 shrink-0">
                <div className="flex items-center gap-3">
                  {previewDocUrl && (
                    <button
                      onClick={() => {
                        URL.revokeObjectURL(previewDocUrl);
                        setPreviewDocUrl(null);
                      }}
                      className="p-1.5 bg-slate-100 hover:bg-slate-200 dark:bg-slate-700 dark:hover:bg-slate-600 rounded-md transition text-slate-600 dark:text-slate-300"
                      title="Back to list"
                    >
                      <ArrowLeft size={16} />
                    </button>
                  )}
                  <h3 className="font-bold text-base text-slate-900 dark:text-slate-100 flex items-center gap-2">
                    <FileText className="text-blue-600" size={20} />
                    {previewDocUrl ? "Document Preview" : "HRA Slip Documents"}
                  </h3>
                </div>
                <button
                  onClick={closeHraSlipModal}
                  className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
                >
                  <X size={20} />
                </button>
              </div>

              {previewDocUrl ? (
                <div className="flex-1 bg-slate-100 dark:bg-slate-900 rounded-lg overflow-hidden relative min-h-[400px]">
                  <iframe
                    src={previewDocUrl}
                    className="w-full h-full border-0"
                    title="Document Preview"
                  />
                </div>
              ) : (
                <>
                  {hraSlipLoading ? (
                    <div className="flex items-center gap-2 text-xs text-slate-400 py-4">
                      <Loader2 size={14} className="animate-spin" /> Loading documents…
                    </div>
                  ) : hraSlipDocuments.length === 0 ? (
                    <p className="text-xs text-slate-500 dark:text-slate-400 py-4">
                      No HRA slip documents found.
                    </p>
                  ) : (
                    <div className="space-y-2">
                      {hraSlipDocuments.map((doc) => (
                        <div
                          key={doc.id}
                          className="w-full flex items-center justify-between p-3 border border-slate-200 dark:border-slate-700 rounded-lg bg-slate-50 dark:bg-slate-700/30 text-left"
                        >
                          <div className="flex items-center gap-2 flex-1 min-w-0">
                            <FileText size={16} className="text-blue-600 dark:text-blue-400 shrink-0" />
                            <span className="text-xs font-medium text-slate-700 dark:text-slate-300 truncate">
                              HRA Slip - {new Date(doc.uploadedAt).toLocaleDateString('en-IN')}
                            </span>
                          </div>
                          <div className="flex items-center gap-2 ml-3 shrink-0">
                            <button
                              onClick={() => handlePreviewHraSlip(doc.id)}
                              className="p-1.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-600 rounded-md text-slate-600 dark:text-slate-300 hover:text-blue-600 hover:border-blue-300 dark:hover:text-blue-400 transition"
                              title="Preview on screen"
                            >
                              <Eye size={15} />
                            </button>
                            <button
                              onClick={() => handleDownloadHraSlip(doc.id)}
                              className="p-1.5 bg-blue-50 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-800 rounded-md text-blue-600 dark:text-blue-400 hover:bg-blue-100 dark:hover:bg-blue-900/50 transition"
                              title="Download"
                            >
                              <Download size={15} />
                            </button>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}

                  <div className="flex justify-end pt-2">
                    <button
                      onClick={closeHraSlipModal}
                      className="px-4 py-2 bg-slate-200 dark:bg-slate-700 text-slate-800 dark:text-slate-200 text-xs font-semibold rounded-lg hover:bg-slate-300 dark:hover:bg-slate-600 transition"
                    >
                      Close
                    </button>
                  </div>
                </>
              )}
            </div>
          </div>
        )}

        {showStipendFormModal && activeStipendClaim && (
          <StipendFormModal
            claim={activeStipendClaim}
            onClose={closeStipendFormModal}
            canUpload={canActOn(activeStipendClaim) && (isFaculty || isHOD)}
            showToast={showToast}
          />
        )}

        {showProcessModal && selectedClaim && (
          <ProcessClaimModal
            claim={selectedClaim}
            isHOD={isHOD}
            initialAmount={selectedClaim.recommendedAmount}
            onClose={() => setShowProcessModal(false)}
            onProcessed={() => {
              setShowProcessModal(false);
              loadData();
            }}
            showToast={showToast}
          />
        )}
      </div>
    </div>
  );
}
