// <auto-generated />
using System;
using API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260817050324_AddResubmitEntrySequence")]
    partial class AddResubmitEntrySequence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Domain.Entities.Advertisement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("CandidateCountAtClose")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ClosingDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PublishedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("RecruitmentRequestId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RecruitmentRequestId", "Round")
                        .IsUnique();

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("API.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ExternalLink")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("external_link");

                    b.Property<decimal>("FundingAmount")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("funding_amount");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pdf_path");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.BudgetHead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("HeadName")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Year1Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Year2Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Year3Amount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "HeadName")
                        .IsUnique();

                    b.ToTable("BudgetHeads");
                });

            modelBuilder.Entity("API.Domain.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Experience")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("InterviewMode")
                        .HasColumnType("int");

                    b.Property<int?>("MeritRank")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OnlineModeApprovedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<Guid?>("PrefilledFromCandidateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Qualification")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RecruitmentRequestId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ScreeningResult")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RecruitmentRequestId", "ApplicationUserId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("API.Domain.Entities.Collaborator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Collaborators");
                });

            modelBuilder.Entity("API.Domain.Entities.CommitteeMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("AvailabilityDate")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RecruitmentRequestId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SignedMeritListAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RecruitmentRequestId", "Kind");

                    b.ToTable("CommitteeMembers");
                });

            modelBuilder.Entity("API.Domain.Entities.ConsumableIndent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BudgetHeadId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EWayBillNumber")
                        .HasColumnType("longtext");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("GemAvailability")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("NonAvailabilityCertificateIssueDate")
                        .HasColumnType("date");

                    b.Property<string>("NonAvailabilityCertificateNumber")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("NonAvailabilityCertificateValidityDate")
                        .HasColumnType("date");

                    b.Property<string>("OriginalBillReference")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("StockActualCost")
                        .HasColumnType("longtext");

                    b.Property<string>("StockBookPage")
                        .HasColumnType("longtext");

                    b.Property<string>("StockCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("StockDescription")
                        .HasColumnType("longtext");

                    b.Property<bool>("StockEntryConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StockQuantity")
                        .HasColumnType("longtext");

                    b.Property<string>("TechnicalSpecs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnitOfMeasurement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetHeadId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("ConsumableIndents");
                });

            modelBuilder.Entity("API.Domain.Entities.ContingencyIndent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BudgetHeadId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EWayBillNumber")
                        .HasColumnType("longtext");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("GemAvailability")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("NonAvailabilityCertificateIssueDate")
                        .HasColumnType("date");

                    b.Property<string>("NonAvailabilityCertificateNumber")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("NonAvailabilityCertificateValidityDate")
                        .HasColumnType("date");

                    b.Property<string>("OriginalBillReference")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("StockActualCost")
                        .HasColumnType("longtext");

                    b.Property<string>("StockBookPage")
                        .HasColumnType("longtext");

                    b.Property<string>("StockCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("StockDescription")
                        .HasColumnType("longtext");

                    b.Property<bool>("StockEntryConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StockQuantity")
                        .HasColumnType("longtext");

                    b.Property<string>("TechnicalSpecs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnitOfMeasurement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetHeadId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("ContingencyIndents");
                });

            modelBuilder.Entity("API.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("HeadUserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInstituteWide")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("API.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("API.Domain.Entities.DocumentChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DocumentKind")
                        .HasColumnType("int");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestType", "Phase");

                    b.ToTable("DocumentChecklistItems");
                });

            modelBuilder.Entity("API.Domain.Entities.EquipmentIndent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BudgetHeadId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EWayBillNumber")
                        .HasColumnType("longtext");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("GemAvailability")
                        .HasColumnType("int");

                    b.Property<string>("MeasurementBookNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("NonAvailabilityCertificateIssueDate")
                        .HasColumnType("date");

                    b.Property<string>("NonAvailabilityCertificateNumber")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("NonAvailabilityCertificateValidityDate")
                        .HasColumnType("date");

                    b.Property<string>("OriginalBillReference")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SanctionedEquipmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StockActualCost")
                        .HasColumnType("longtext");

                    b.Property<string>("StockBookPage")
                        .HasColumnType("longtext");

                    b.Property<string>("StockCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("StockDescription")
                        .HasColumnType("longtext");

                    b.Property<bool>("StockEntryConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StockQuantity")
                        .HasColumnType("longtext");

                    b.Property<string>("TechnicalSpecs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnitOfMeasurement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetHeadId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SanctionedEquipmentId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("EquipmentIndents");
                });

            modelBuilder.Entity("API.Domain.Entities.Expenditure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Expenditure");
                });

            modelBuilder.Entity("API.Domain.Entities.FacultyProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_id");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("department");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("designation");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gender");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("joining_date");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("photo");

                    b.Property<string>("Qualification")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("qualification");

                    b.Property<string>("ResearchArea")
                        .HasColumnType("text")
                        .HasColumnName("research_area");

                    b.HasKey("UserId");

                    b.ToTable("faculty_profiles", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.FacultyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("faculty_users", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.FellowshipClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ClaimMonth")
                        .HasColumnType("int");

                    b.Property<int>("ClaimYear")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FellowAppointmentId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("FellowshipAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("HraAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("HraClaimed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("HraOverriddenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("HraOverriddenByUserId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("HraOverrideAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("HraOverrideReason")
                        .HasColumnType("longtext");

                    b.Property<int>("LeaveDaysTakenThisMonth")
                        .HasColumnType("int");

                    b.Property<decimal?>("RecommendedAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UnauthorisedAbsenceDays")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("FellowAppointmentId", "ClaimYear", "ClaimMonth")
                        .IsUnique();

                    b.ToTable("FellowshipClaims");
                });

            modelBuilder.Entity("API.Domain.Entities.GrantReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("BudgetHeadId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ParentReceiptId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("PaymentMode")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<int?>("SubHead")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetHeadId");

                    b.HasIndex("ParentReceiptId");

                    b.HasIndex("ProjectId");

                    b.ToTable("GrantReceipts");
                });

            modelBuilder.Entity("API.Domain.Entities.LeaveEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ConsumedDays")
                        .HasColumnType("int");

                    b.Property<int>("EntitledDays")
                        .HasColumnType("int");

                    b.Property<Guid>("FellowAppointmentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("LeaveType")
                        .HasColumnType("int");

                    b.Property<int>("ProjectYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FellowAppointmentId", "LeaveType", "ProjectYear")
                        .IsUnique();

                    b.ToTable("LeaveEntitlements");
                });

            modelBuilder.Entity("API.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DayCount")
                        .HasColumnType("int");

                    b.Property<Guid>("FellowAppointmentId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveType")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FellowAppointmentId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("API.Domain.Entities.ManpowerSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AadharNo")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BankAccountNo")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("IdCardIssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdCardNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("IfscCode")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("date");

                    b.Property<string>("PanNo")
                        .HasColumnType("longtext");

                    b.Property<decimal>("RecommendedStipend")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("SanctionedManpowerPositionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ValidTill")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("CandidateId")
                        .IsUnique();

                    b.HasIndex("SanctionedManpowerPositionId");

                    b.ToTable("FellowAppointments", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("API.Domain.Entities.NewsEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("news_events", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.NewsImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsTitle")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_title");

                    b.Property<int>("NewsId")
                        .HasColumnType("int")
                        .HasColumnName("news_id");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("news_images", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsNavigable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("ModuleId");

                    b.HasIndex("Route")
                        .IsUnique();

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("API.Domain.Entities.ProcurementCommittee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IndentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("IndentType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndentType", "IndentId");

                    b.ToTable("ProcurementCommittees");
                });

            modelBuilder.Entity("API.Domain.Entities.ProcurementCommitteeMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProcurementCommitteeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcurementCommitteeId");

                    b.ToTable("ProcurementCommitteeMembers");
                });

            modelBuilder.Entity("API.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SanctionDate")
                        .HasColumnType("date");

                    b.Property<string>("SanctionNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalSanctioned")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("API.Domain.Entities.RecruitmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AdvertisementRound")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("InterviewDate")
                        .HasColumnType("date");

                    b.Property<string>("InterviewVenue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SanctionedManpowerPositionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<Guid?>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SanctionedManpowerPositionId");

                    b.ToTable("RecruitmentRequests");
                });

            modelBuilder.Entity("API.Domain.Entities.RolePageAccess", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PageId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PageId");

                    b.HasIndex("PageId");

                    b.ToTable("RolePageAccess");
                });

            modelBuilder.Entity("API.Domain.Entities.SanctionedEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("SanctionedEquipment");
                });

            modelBuilder.Entity("API.Domain.Entities.SanctionedManpowerPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Hra")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Positions")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Stipend")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("SanctionedManpowerPositions");
                });

            modelBuilder.Entity("API.Domain.Entities.TravelJourneyLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("BookingPlatform")
                        .HasColumnType("int");

                    b.Property<DateOnly>("JourneyDate")
                        .HasColumnType("date");

                    b.Property<string>("JourneyFrom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JourneyTo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TravelRequestId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TravelRequestId");

                    b.ToTable("TravelJourneyLegs");
                });

            modelBuilder.Entity("API.Domain.Entities.TravelRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("AccommodationCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AccommodationDetails")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("BudgetHeadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CoPiDesignation")
                        .HasColumnType("longtext");

                    b.Property<string>("CoPiName")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ExpectedCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("JourneyTotalCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("ManpowerId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("OnwardDate")
                        .HasColumnType("date");

                    b.Property<string>("OriginalBillReference")
                        .HasColumnType("longtext");

                    b.Property<decimal>("OtherExpensesCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("OtherExpensesDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PrimaryMode")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("TaxiCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("TaxiReimbursementOptedIn")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TravelerType")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetHeadId");

                    b.HasIndex("ManpowerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("TravelRequests");
                });

            modelBuilder.Entity("API.Domain.Entities.UserPageGrant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PageId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PageId");

                    b.HasIndex("PageId");

                    b.ToTable("UserPageGrants");
                });

            modelBuilder.Entity("API.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<int?>("ResubmitEntrySequence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RequestType", "Phase")
                        .IsUnique();

                    b.ToTable("WorkflowDefinitions");
                });

            modelBuilder.Entity("API.Domain.Entities.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestType", "RequestId");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("API.Domain.Entities.WorkflowStageDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AllowedRoles")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<bool>("CanApprove")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanReject")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInitial")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId", "Sequence")
                        .IsUnique();

                    b.ToTable("WorkflowStageDefinitions");
                });

            modelBuilder.Entity("API.Domain.Entities.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.Advertisement", b =>
                {
                    b.HasOne("API.Domain.Entities.RecruitmentRequest", "RecruitmentRequest")
                        .WithMany("Advertisements")
                        .HasForeignKey("RecruitmentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecruitmentRequest");
                });

            modelBuilder.Entity("API.Domain.Entities.BudgetHead", b =>
                {
                    b.HasOne("API.Domain.Entities.Project", null)
                        .WithMany("BudgetHeads")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("API.Domain.Entities.RecruitmentRequest", "RecruitmentRequest")
                        .WithMany("Candidates")
                        .HasForeignKey("RecruitmentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecruitmentRequest");
                });

            modelBuilder.Entity("API.Domain.Entities.Collaborator", b =>
                {
                    b.HasOne("API.Domain.Entities.Project", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.CommitteeMember", b =>
                {
                    b.HasOne("API.Domain.Entities.RecruitmentRequest", "RecruitmentRequest")
                        .WithMany("CommitteeMembers")
                        .HasForeignKey("RecruitmentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecruitmentRequest");
                });

            modelBuilder.Entity("API.Domain.Entities.EquipmentIndent", b =>
                {
                    b.HasOne("API.Domain.Entities.SanctionedEquipment", null)
                        .WithMany()
                        .HasForeignKey("SanctionedEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.GrantReceipt", b =>
                {
                    b.HasOne("API.Domain.Entities.GrantReceipt", null)
                        .WithMany()
                        .HasForeignKey("ParentReceiptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Domain.Entities.Project", null)
                        .WithMany("GrantReceipts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.ManpowerSelection", b =>
                {
                    b.HasOne("API.Domain.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("API.Domain.Entities.NewsImage", b =>
                {
                    b.HasOne("API.Domain.Entities.NewsEvent", "NewsEvent")
                        .WithMany("Images")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsEvent");
                });

            modelBuilder.Entity("API.Domain.Entities.Page", b =>
                {
                    b.HasOne("API.Domain.Entities.Module", "Module")
                        .WithMany("Pages")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("API.Domain.Entities.ProcurementCommitteeMember", b =>
                {
                    b.HasOne("API.Domain.Entities.ProcurementCommittee", null)
                        .WithMany("Members")
                        .HasForeignKey("ProcurementCommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.RolePageAccess", b =>
                {
                    b.HasOne("API.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("API.Domain.Entities.SanctionedEquipment", b =>
                {
                    b.HasOne("API.Domain.Entities.Project", null)
                        .WithMany("SanctionedEquipment")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.SanctionedManpowerPosition", b =>
                {
                    b.HasOne("API.Domain.Entities.Project", null)
                        .WithMany("SanctionedManpowerPositions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.TravelJourneyLeg", b =>
                {
                    b.HasOne("API.Domain.Entities.TravelRequest", "TravelRequest")
                        .WithMany("Journeys")
                        .HasForeignKey("TravelRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelRequest");
                });

            modelBuilder.Entity("API.Domain.Entities.TravelRequest", b =>
                {
                    b.HasOne("API.Domain.Entities.SanctionedManpowerPosition", null)
                        .WithMany()
                        .HasForeignKey("ManpowerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("API.Domain.Entities.UserPageGrant", b =>
                {
                    b.HasOne("API.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("API.Domain.Entities.WorkflowStageDefinition", b =>
                {
                    b.HasOne("API.Domain.Entities.WorkflowDefinition", "Definition")
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("API.Domain.Entities.WorkflowStep", b =>
                {
                    b.HasOne("API.Domain.Entities.WorkflowInstance", null)
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("API.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("API.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("API.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Domain.Entities.Module", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("API.Domain.Entities.NewsEvent", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("API.Domain.Entities.ProcurementCommittee", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("API.Domain.Entities.Project", b =>
                {
                    b.Navigation("BudgetHeads");

                    b.Navigation("Collaborators");

                    b.Navigation("GrantReceipts");

                    b.Navigation("SanctionedEquipment");

                    b.Navigation("SanctionedManpowerPositions");
                });

            modelBuilder.Entity("API.Domain.Entities.RecruitmentRequest", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("Candidates");

                    b.Navigation("CommitteeMembers");
                });

            modelBuilder.Entity("API.Domain.Entities.TravelRequest", b =>
                {
                    b.Navigation("Journeys");
                });

            modelBuilder.Entity("API.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("API.Domain.Entities.WorkflowInstance", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
