import { apiBlob, apiGet, apiPost, apiPut } from './apiClient';

// --- Fellow-facing ----------------------------------------------------------

export const raiseFellowshipClaim = (payload) =>
  apiPost('/api/fellowship-claims', payload);

/** Edit a rejected fellowship claim to resubmit it. */
export const editRejectedClaim = (claimId, payload) =>
  apiPut(`/api/fellowship-claims/${claimId}/edit-rejected`, payload);

export const getMyAppointmentId = () => apiGet('/api/my/fellowship-appointment/id');

export const listMyClaims = () => apiGet('/api/my/fellowship-claims');

export const listAllFellowshipClaims = () => apiGet('/api/fellowship-claims');

/** All fellowship claims from the calling PI's own projects. */
export const listMyProjectFellowshipClaims = () =>
  apiGet('/api/my/project-fellowship-claims');
export const getMyAppointment = () => apiGet('/api/my/fellowship-appointment');

export const getMyStipendFormDraft = (year, month) =>
  apiGet(`/api/my/stipend-form-draft?year=${year}&month=${month}`);

export const getClaim = (claimId) => apiGet(`/api/fellowship-claims/${claimId}`);

export const getStipendFormData = (claimId) =>
  apiGet(`/api/fellowship-claims/${claimId}/form-data`);

/** Ordered workflow history for a claim (Raise → approve/reject/return steps). */
export const getClaimSteps = (claimId) =>
  apiGet(`/api/fellowship-claims/${claimId}/steps`);

export const raiseLeaveRequest = (payload) => apiPost('/api/leave-requests', payload);

export const listMyLeaveRequests = () => apiGet('/api/my/leave-requests');

export const listAllLeaveRequests = () => apiGet('/api/leave-requests');

export const getMyLeaveBalance = () => apiGet('/api/my/leave-balance');

// --- PI-facing --------------------------------------------------------------

export const listClaimsForProject = (projectId) =>
  apiGet(`/api/projects/${projectId}/fellowship-claims`);

/** The PI's figure, entered rather than computed from leave. */
export const recommendAmount = (claimId, payload) =>
  apiPost(`/api/fellowship-claims/${claimId}/recommend`, payload);

export const consumeLeave = (leaveRequestId) =>
  apiPost(`/api/leave-requests/${leaveRequestId}/consume`, {});

export const raiseLeaveCancellation = (leaveRequestId, payload) =>
  apiPost(`/api/leave-requests/${leaveRequestId}/cancellations`, payload);

export const refundLeaveCancellation = (cancellationId) =>
  apiPost(`/api/leave-cancellations/${cancellationId}/refund`, {});

// --- Approval workflow actions -----------------------------------------------

export const approveClaim = (claimId, remarks) =>
  apiPost(`/api/fellowship-claims/${claimId}/approve`, { Remarks: remarks ?? null });

export const rejectClaim = (claimId, remarks) =>
  apiPost(`/api/fellowship-claims/${claimId}/reject`, { Remarks: remarks });

export const returnClaim = (claimId, remarks) =>
  apiPost(`/api/fellowship-claims/${claimId}/return`, { Remarks: remarks });

export const withdrawClaim = (claimId, remarks) =>
  apiPost(`/api/fellowship-claims/${claimId}/withdraw`, { remarks });

export const withdrawLeaveRequest = (leaveRequestId, remarks) =>
  apiPost(`/api/leave-requests/${leaveRequestId}/withdraw`, { remarks });

// --- Dean / Director --------------------------------------------------------

/** Overrides the computed 20% HRA. Requires a reason; the server enforces both. */
export const overrideHra = (claimId, payload) =>
  apiPost(`/api/fellowship-claims/${claimId}/override-hra`, payload);

// --- Documents --------------------------------------------------------------

/**
 * Get HRA slip documents uploaded for a fellow appointment.
 */
export const getHraSlipDocuments = (claimId) =>
  apiGet(`/api/fellowship-claims/${claimId}/hra-slips`);

/**
 * Rendered on demand rather than stored, since the form reflects the live claim
 * including any override and the PI's recommended amount.
 */
export async function downloadStipendForm(claimId) {
  const blob = await apiBlob(`/api/fellowship-claims/${claimId}/stipend-form`);

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `stipend-form-${claimId}.pdf`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

export const getAutoGeneratedStipendFormBlob = (claimId) =>
  apiBlob(`/api/fellowship-claims/${claimId}/stipend-form`);

export const getSignedStipendFormMetadata = (claimId) =>
  apiGet(`/api/fellowship-claims/${claimId}/signed-stipend-form`);

export const bulkActOnClaims = (claimIds, action, remarks) =>
  apiPost('/api/fellowship-claims/bulk-action', { claimIds, action, remarks: remarks ?? null });

/** The DA/Superintendent/DR/Dean bulk-select queue's data source -- narrowed
 * to claims actually pending the caller's action (per-DA assignment included),
 * unlike listAllFellowshipClaims which is institute-wide/unfiltered. */
export const listPendingClaimsForCaller = () =>
  apiGet('/api/fellowship-claims/pending-for-caller');

export const listReadyToVoucherClaims = () =>
  apiGet('/api/fellowship-claims/ready-to-voucher');

/** voucherDetails: { coordinatorNameDept, projectSanctionNo, paymentTo, fundingAgency } */
export const createVoucherFromClaims = (claimIds, voucherDetails) =>
  apiPost('/api/fellowship-claims/create-voucher', { claimIds, ...voucherDetails });
